### ISSUE TITLE
Feature request: Add an option to choose the image format

### ISSUE THREAD

**Issue by d9beuD** [lawmurray/jekyll-responsive-magick#3]
Currently, generated responsive images are `.png` files. Now that more efficient formats like `.webp` files are [well supported](https://caniuse.com/webp) by all browsers, it would be great to be able to choose the output format.

I think about something like the following:

```yaml
# _config.yml

responsive:
  widths: [...]
  format: webp # the file extension for the ImageMagick `convert` command
```

What do you think about this feature @lawmurray?
